name: Code coverage
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies (workspaces)
        run: npm ci --workspaces --ignore-scripts
      - name: Run tests and collect coverage
        run: npm run test:cov
        working-directory: ./packages/core/manifest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: mnfst/manifest
