name: Release Drafter

on:
  push:
    tags:
      - 'manifest@*.*.*' # Match tags for "manifest"
      - '@mnfst/sdk@*.*.*' # Match tags for "@mnfst/sdk"
      - 'add-manifest@*.*.*' # Match tags for "add-manifest"
  workflow_dispatch: # Allow manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Run Release Drafter to draft and publish the release
      - name: Draft and Publish Release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
